import { StyleSheet, Dimensions } from 'react-native';
import { ThemeColors } from '../context/Themecontext';

const { width, height } = Dimensions.get('window');

export const createAddEntryStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: colors.headerBg,
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: colors.cardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    backButton: {
      padding: 4,
      borderRadius: 8,
    },
    backButtonText: {
      fontSize: 15,
      color: colors.primary,
      fontWeight: '600',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.3,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    themeToggle: {
      width: 44,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.toggleTrack,
      justifyContent: 'center',
      paddingHorizontal: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    themeToggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.toggleThumb,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    themeToggleThumbDark: {
      transform: [{ translateX: 18 }],
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 100,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      marginBottom: 10,
      marginTop: 10,
    },
    photoArea: {
      width: '100%',
      height: height * 0.32,
      borderRadius: 18,
      overflow: 'hidden',
      backgroundColor: colors.surface,
      borderWidth: 2,
      borderColor: colors.border,
      borderStyle: 'dashed',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    photoAreaFilled: {
      borderStyle: 'solid',
      borderColor: colors.primary,
    },
    photoPlaceholder: {
      alignItems: 'center',
    },
    photoPlaceholderIcon: {
      fontSize: 52,
      marginBottom: 12,
    },
    photoPlaceholderText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: 4,
    },
    photoPlaceholderSub: {
      fontSize: 13,
      color: colors.textMuted,
    },
    takenPhoto: {
      width: '100%',
      height: '100%',
    },
    cameraButton: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
      marginBottom: 8,
    },
    retakeButton: {
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    cameraButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    retakeButtonText: {
      color: colors.text,
    },
    cameraButtonIcon: {
      fontSize: 18,
    },
    addressCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginTop: 4,
    },
    addressCardRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    addressIcon: {
      fontSize: 20,
      marginRight: 10,
      marginTop: 1,
    },
    addressTextBlock: {
      flex: 1,
    },
    addressLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textMuted,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    addressText: {
      fontSize: 15,
      color: colors.text,
      fontWeight: '500',
      lineHeight: 22,
    },
    addressLoading: {
      fontSize: 14,
      color: colors.textMuted,
      fontStyle: 'italic',
    },
    addressPlaceholder: {
      fontSize: 14,
      color: colors.textMuted,
      fontStyle: 'italic',
    },
    coordsRow: {
      flexDirection: 'row',
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 16,
    },
    coordItem: {
      flex: 1,
    },
    coordLabel: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    coordValue: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
      marginTop: 2,
    },
    errorContainer: {
      backgroundColor: colors.dangerLight,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.danger,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    errorIcon: {
      fontSize: 18,
    },
    errorText: {
      flex: 1,
      fontSize: 14,
      color: colors.danger,
      lineHeight: 20,
      fontWeight: '500',
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 8,
    },
    saveButtonWrapper: {
      marginTop: 28,
    },
    saveButton: {
      backgroundColor: colors.primary,
      borderRadius: 16,
      paddingVertical: 16,
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 10,
      elevation: 6,
    },
    saveButtonDisabled: {
      backgroundColor: colors.border,
      shadowOpacity: 0,
      elevation: 0,
    },
    saveButtonText: {
      fontSize: 17,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    saveButtonSub: {
      fontSize: 12,
      color: 'rgba(255,255,255,0.7)',
      marginTop: 3,
    },
    permissionCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 24,
      margin: 20,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    permissionIcon: {
      fontSize: 48,
      marginBottom: 16,
    },
    permissionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 10,
    },
    permissionText: {
      fontSize: 14,
      color: colors.textMuted,
      textAlign: 'center',
      lineHeight: 22,
      marginBottom: 20,
    },
    permissionButton: {
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 28,
    },
    permissionButtonText: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: 15,
    },
    successBanner: {
      backgroundColor: colors.success + '20',
      borderRadius: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.success,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: 8,
    },
    successIcon: {
      fontSize: 18,
    },
    successText: {
      flex: 1,
      fontSize: 14,
      color: colors.success,
      fontWeight: '500',
    },
  });