import { StyleSheet, Dimensions } from 'react-native';
import { ThemeColors } from '../context/Themecontext';

const { width } = Dimensions.get('window');

export const createHomeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: colors.headerBg,
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: colors.cardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    headerLeft: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    headerSubtitle: {
      fontSize: 13,
      color: colors.textMuted,
      marginTop: 2,
      fontStyle: 'italic',
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    themeToggle: {
      width: 53,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.toggleTrack,
      justifyContent: 'center',
      paddingHorizontal: 3,
      borderWidth: 1,
      borderColor: colors.border,
    },
    themeToggleThumb: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.toggleThumb,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    themeIcon: {
      position: 'absolute',
      left: 10,
    },
    themeToggleThumbDark: {
      transform: [{ translateX: 22 }],
    },
    addButton: {
      backgroundColor: colors.primary,
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.35,
      shadowRadius: 6,
      elevation: 4,
    },
    addButtonText: {
      fontSize: 22,
      color: '#FFFFFF',
      fontWeight: '300',
      lineHeight: 26,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 100,
    },
    entryCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      marginBottom: 16,
      overflow: 'hidden',
      shadowColor: colors.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 5,
      borderWidth: 1,
      borderColor: colors.border,
    },
    entryImage: {
      width: '100%',
      height: 200,
      backgroundColor: colors.border,
    },
    entryFooter: {
      padding: 14,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    entryInfo: {
      flex: 1,
      marginRight: 12,
    },
    entryAddressRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 6,
    },
    pinIcon: {
      fontSize: 14,
      marginRight: 5,
      marginTop: 1,
    },
    entryAddress: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
      lineHeight: 20,
    },
    entryDate: {
      fontSize: 12,
      color: colors.textMuted,
      marginLeft: 19,
      fontStyle: 'italic',
    },
    removeButton: {
      backgroundColor: colors.dangerLight,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.danger,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },

    removeButtonText: {
      fontSize: 12,
      color: colors.danger,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    emptyContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: 80,
    },
    emptyIconCircle: {
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: colors.emptyIcon,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    emptyIcon: {
      fontSize: 50,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 15,
      color: colors.textMuted,
      textAlign: 'center',
      lineHeight: 22,
      paddingHorizontal: 40,
    },
    subemptyText: {
      fontSize: 13,
      color: colors.textInstruct,
    },
    countBadge: {
      backgroundColor: colors.primaryLight,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      marginTop: 6,
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: colors.primary,
    },
    countBadgeText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '700',
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 15,
      color: colors.textMuted,
    },
    errorBanner: {
      backgroundColor: colors.dangerLight,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.danger,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    errorBannerText: {
      color: colors.danger,
      fontSize: 13,
      flex: 1,
      fontWeight: '500',
    },
    errorBannerDismiss: {
      color: colors.danger,
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 8,
    },
  });